version: '2.1'

services:

  postgres_test:
    image: postgres
    environment:
      POSTGRES_PASSWORD: ${TEST_DB_PASSWORD}
      POSTGRES_USER: ${TEST_DB_USERNAME}
      POSTGRES_DB: ${TEST_DB_NAME}
    volumes:
      - pgdata_test:/var/lib/postgresql/data

  api_test:

    build:
      context: ./
      dockerfile: Dockerfile

    # Import .env data to api environment
    env_file: ./.env

    environment:
      DB_HOST: 'database'
      ENVIRONMENT: "test"

    depends_on:
      - postgres_test
    links:
      - postgres_test:database

    entrypoint: ./docker-entrypoint.sh

    # Link the host src code to the container
    volumes:
      - ./src/:/home/workspace/api/src

# Database volume
volumes:
  pgdata_test: